[tox]
envlist = py38, py312, type, lint

[testenv]
deps = 
    pytest
    pytest-regressions
    playwright
commands =
    pytest tests/

[testenv:type]
deps = mypy
commands = mypy src/

[testenv:lint]
deps = ruff
commands = ruff check src/
